### ISSUE TITLE
When will release the code?

### ISSUE THREAD

**Issue by junwenxiong** [soumik-kanad/diff2lip#1]

**Comment by WudiJoey** [comment]
bro， i also want to know.

**Comment by wwqy** [comment]
bro， i also want to know.

**Comment by hippotabek** [comment]
+

**Comment by WudiJoey** [comment]
您好，您的来信我已经收到，会尽快回复。

**Comment by soumik-kanad** [comment]
Hi, 
@junwenxiong @wwqy @hippotabek @WudiJoey 
Inference code and models have been released.

**Comment by Inferencer** [comment]
Hello Soumik sorry for re-opening this issue but you you also release the training code

**Comment by WudiJoey** [comment]
您好，您的来信我已经收到，会尽快回复。
