### ISSUE TITLE
About temporal consistency

### ISSUE THREAD

**Issue by chunyu-li** [soumik-kanad/diff2lip#11]
I noticed that the temporal consistency of Diff2Lip is good. What tricks did you apply in model training? Did you simply concatenate multiple continous frames in batch dimension to achieve this?

**Comment by soumik-kanad** [comment]
We used temporal losses like sequence discriminator during training for better temporal consistency. And at inference time, we use (1) the input frames as the reference input as well and (2) the same initial gaussian noise for the ddim sampling process across all frames.
