### ISSUE TITLE
Inference in Windows

### ISSUE THREAD

**Issue by crockrocks** [soumik-kanad/diff2lip#16]
When running in windows with cuda as well as without cuda I found out that the backends that is nccl and gloo are not being supported and it throws an error .
Any workaround for that?

**Comment by soumik-kanad** [comment]
It seems that windows only supports gloo with file store. ( https://discuss.pytorch.org/t/multi-gpu-training-on-windows-10/100207/7 ) 
I am unable to test on windows. I request that someone working on windows please take a look to update this codebase for windows and send a pull request.

Meanwhile, possible workarounds are that you can run the codebase on Google colab. Or maybe remove all the distributed code and run on a single GPU. (I might be able to help with the latter).

**Comment by crockrocks** [comment]
I was running on a single GPU only , what do you mean by removing all the distributed code ?

**Comment by jags111** [comment]
is it possible to share a colab for running this and testing same. Thanks

**Comment by soumik-kanad** [comment]
@jags111 I have added a colab notebook now.
