### ISSUE TITLE
can you help

### ISSUE THREAD

**Issue by zachysaur** [soumik-kanad/diff2lip#18]
can you simply update where to put audio an video file its bit confusing 
#!/bin/bash

#set paths and arguments
real_video_root='dataset/VoxCeleb2/vox2_test_mp4/mp4/'
model_path="D:\diff2lip-main\checkpoints/e7.24.1.3_model260000_paper.pt"
sample_path="D:\diff2lip-main\result"
sample_mode="cross" # or "reconstruction"
NUM_GPUS=1

**Comment by zachysaur** [comment]
(diff2lip) D:\diff2lip-main>python generate_dist.py
MPI.COMM_WORLD.Get_rank() 0
os.environ["CUDA_VISIBLE_DEVICES"] 0
Logging to d2l_gen
creating model...
Traceback (most recent call last):
  File "D:\diff2lip-main\generate_dist.py", line 428, in <module>
    main()
  File "D:\diff2lip-main\generate_dist.py", line 354, in main
    dist_util.load_state_dict(args.model_path, map_location='cpu')
  File "d:\diff2lip-main\guided-diffusion\guided_diffusion\dist_util.py", line 61, in load_state_dict
    with bf.BlobFile(path, "rb") as f:
  File "C:\Users\ggrov\anaconda3\envs\diff2lip\lib\site-packages\blobfile\_ops.py", line 358, in BlobFile
    return default_context.BlobFile(
  File "C:\Users\ggrov\anaconda3\envs\diff2lip\lib\site-packages\blobfile\_context.py", line 869, in BlobFile
    f = io.FileIO(path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

(diff2lip) D:\diff2lip-main>

**Comment by soumik-kanad** [comment]
Please use the [inference_single_video.sh](https://github.com/soumik-kanad/diff2lip/blob/main/scripts/inference_single_video.sh) for single video inference. 

The second error you shared is because the model path that you specified does not exist.

**Comment by zachysaur** [comment]
what model path

**Comment by zachysaur** [comment]
when i run bash file it just open and close in seconds

**Comment by soumik-kanad** [comment]
Please specify the model_path, video_path, audio_path, out_path properly in the bash script at the top. 

The link to download the models is present in the README.

**Comment by QuantumShot10** [comment]
while running the singleinference.sh it is saying permission denied

**Comment by soumik-kanad** [comment]
@QuantumShot10 Please give appropriate permission to your script before running. On linux it can be done using - 
`chmod 764 scripts/inference_single_video.sh`
