### ISSUE TITLE
Issue about https://github.com/cloneofsimo/lora/issues/258

### ISSUE THREAD

**Issue by BeALigh** [soumik-kanad/diff2lip#22]
Hello,

I am trying to train lora with cloneofsimo/lora and encountered an issue during the process.. I hope you can assist me with them.

Firstly, regarding the setup of the dataset for LORA training, I am interested in understanding how you select and prepare these data. Are there any specific format requirements? Or do they need to undergo certain preprocessing steps? I did not find detailed instructions on this part in your documentation or code, and I would appreciate your guidance.

Secondly, I encountered an error while executing your inference script. The specific error message is as follows:

![image](https://github.com/soumik-kanad/diff2lip/assets/69510692/8f147e47-c130-4ce9-ad57-e2ba17e89b40)

I have checked the relevant code and dependencies but haven't been able to resolve the issue. Is this a known problem? Or can you provide any suggestions to address this issue?

Thank you for your assistance, and I look forward to your reply.

**Comment by soumik-kanad** [comment]
I think you should ask this question in that repo. I may not be able to help you here. 

PS. Seems like a problem with the pipeline's nsfw checker. Take a look at how to remove nsfw checker.
