### ISSUE TITLE
possible to only get the differential output?

### ISSUE THREAD

**Issue by DrBrule** [soumik-kanad/diff2lip#23]
I'm curious if it would be possible to only get the output of the new face movements, and not have the system re-merge the video streams back into one?

**Comment by soumik-kanad** [comment]
I'm unsure what you mean by differential output. We are directly generating the lower mouth portion based on the audio and not the movement. 

There isn't an option right now to get the generation directly. But you can very easily update the generate.py/generate_dist.py around the g, v, b loop.

**Comment by DrBrule** [comment]
Great, I'll poke around in there, thank you!

What I am looking for is just the new layer of mouth movements.   I can re-merge the new video later on with some other tools.
