### ISSUE TITLE
Setting diffusion steps to > 1000 introduces Gaussian noise

### ISSUE THREAD

**Issue by xjtuljy** [soumik-kanad/diff2lip#26]
Hi, thank you for releasing the test code and model.  I'm playing with the "inference_single_video" script, finding that using diffusion steps > 1000 introduces noticeable Gaussian noise. And from another post, I saw that timestep_respacing is the flag to change the denoising steps. How shall I tune them?

**Comment by soumik-kanad** [comment]
I advise not to change that setting.
