### ISSUE TITLE
when finally write the video,it turn out the index error

### ISSUE THREAD

**Issue by like-yo** [soumik-kanad/diff2lip#28]
![image](https://github.com/soumik-kanad/diff2lip/assets/125039272/5f8a41f3-27b5-4523-9aa7-f966615f1488)

**Comment by soumik-kanad** [comment]
This is a Torchvision problem. 
Please take a look at this - 
https://stackoverflow.com/questions/75070838/torch-write-video-throws-indexerror

**Comment by like-yo** [comment]
oh,thank you,it work.Absolutely i enven solve it by trying to make a silent video first and the use the ffmpeg add the audio😂.At the same time,i have a qustion that I don't need to make any chage but work the code nomally at RTX 4090,but when I  turn the code in H800,it turn out the cuda problem，untill i delete the distribute code it can work,and then turn out this torchvision index error😪
