### ISSUE TITLE
Extremely distorted video for reconstruction and cross.

### ISSUE THREAD

**Issue by constan1** [soumik-kanad/diff2lip#3]
So im getting very poor video generation. The entire face is distorted and sometimes I just see the mouth overlay on the face.

I changed nothing. Just ran scripts/inference.sh for a single clear video.

I even preprocessed to 224x224 @ 25fps (as in the paper) and it's not better. Below is an example of a frame from the video

running the e7.24.1.3_model260000_paper.pt checkpoint.

**Comment by soumik-kanad** [comment]
It seems like a face detection problem. 
I'm guessing you need to also change the flag --is_voxceleb2=False. 

Send me an email if that doesn't work.

**Comment by constan1** [comment]
Yes, i fixed it. But I see that there is some overlap on the mouth, overall its good. Are there settings i can play with like padding etc? Maybe change the inpainting size. Is it exactly 0.5 for all face sizes etc?

**Comment by soumik-kanad** [comment]
You can try playing with the padding but I suggest you not change the inpaining size for now as that might affect other things.
