### ISSUE TITLE
GPU not being used

### ISSUE THREAD

**Issue by amirhamdani** [soumik-kanad/diff2lip#31]
Dears,

I successfuly run the scipt but I have an issue, I dont believe that it is using my GPU (RTX A4000), I can see only the GPU and RAM being used.

This is what I get when I run the Script: "scripts\inference_single_video.sh"
**MPI.COMM_WORLD.Get_rank() 0
os.environ["CUDA_VISIBLE_DEVICES"] 0
Logging to d2l_gen
creating model...**

Any advice please?

Thanks

**Comment by soumik-kanad** [comment]
Please check that you have specified the paths properly. 
Do you see any errors or directories being formed when the script runs?

Also there is a known error issues with Windows.
