### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by HppZ** [soumik-kanad/diff2lip#33]
It seems that VoxCeleb2 is not available to download.

**Comment by soumik-kanad** [comment]
For inference, you do not need the dataset.

**Comment by HppZ** [comment]
then how to set `real_video_root` variable?

**Comment by soumik-kanad** [comment]
Use the `inference_single_video.sh` script if you are not trying to do Voxceleb2 inference.

**Comment by soumik-kanad** [comment]
Or you can also try the Colab notebook.

**Comment by soumik-kanad** [comment]
It does seem like VoxCeleb2 can no longer be downloaded from [their website](https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox2.html). I suggest you email the authors of VoxCeleb2 and see what they say.
