### ISSUE TITLE
Running on mac m1 

### ISSUE THREAD

**Issue by keystabbs** [soumik-kanad/diff2lip#35]
Hello, I realize that many dependencies are designed to work with nvidia, but is there any way to run the process on apple? I lack the knowledge to fix Requirements and inference, trying a lot but can't win yet. 

Can you guide me, or tell me how to do it? If it is even possible

**Comment by soumik-kanad** [comment]
Yeah, you need a GPU to run this code. I have never tried it on CPU or non Linux devices. 
Please use the colab notebook, that way you can try it even on a browser.

**Comment by keystabbs** [comment]
Thanks, I understand, but as I see in google collab the option without VoxCeleb2. Where in this case to specify in the code the reference to the dataset?

**Comment by soumik-kanad** [comment]
The colab notebook currently can run 1 video at a time. It is for demo purposes not for running over a dataset. (You could always run it in a loop, but you would need to upload the video files which might not be feasible)

I don't think it is feasible to run this model over a dataset without a GPU (locally on am M1 machine).
