### ISSUE TITLE
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000

### ISSUE THREAD

**Issue by LuckyNES** [soumik-kanad/diff2lip#39]
I use Windows 11 and followed the install instructions exactly. When I run, I get the error in the title.

RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000

I asked Chat GPT how to solve it, just because I have no idea.

"The error message you're encountering suggests that the version of NumPy you are using is incompatible with a compiled binary or module that requires an older version of the Python ABI (Application Binary Interface). The current version of NumPy is using ABI version 0x2000000, but the module you are trying to use was compiled against an older ABI version 0x1000009.

To solve this problem, you need to downgrade NumPy to a version compatible with the older ABI version (0x1000009), which corresponds to a previous version of NumPy."

I did mess around with trying to downgrade numpy but then other packages complain. I tried upgrading everything but got different issues instead. Can the requirements.txt and program be fixed to avoid this error?

Here is the command I use when running:
python generate.py --model_path .\checkpoints\e7.24.1.3_model260000_paper.pt --video_path 'D:\Downloads\testvideo.mp4' --audio_path 'D:\AIOutput\speech\slow.wav' --out_path 'D:\AIOutput\videos\testoutput' --is_voxceleb2=False

**Comment by soumik-kanad** [comment]
I have not tested the codebases in Windows and there are some known issues with windows. 

You can try our colab notebook instead for now.

**Comment by LuckyNES** [comment]
I made it work on Windows 11. No need for the notebook.

**Comment by STEEGMVNN** [comment]
Hello @LuckyNES,

What did you do to make it work?

Thanks!!
