### ISSUE TITLE
Diffusion iterations

### ISSUE THREAD

**Issue by NikitaKononov** [soumik-kanad/diff2lip#7]
Hello, thank you for your great work!

As you had mentioned in paper, you used 25 denoising iterations on inference for better speed
I'd like to change that parameter for experiments, but I can't find it in argparser and model files
Is that possible?

Thanks

**Comment by soumik-kanad** [comment]
`--timestep_respacing ddim25 --use_ddim True` are the flags that control that parameter and are inherited from the guided-diffusion repo. You can change ddim25 to ddim100 for 100 steps of ddim. 

But our model has only been tested for ddim25 and hence I'm not sure how changing this affects the output.
